### ISSUE TITLE
Makefile:11426: recipe for target 'test/test_test_xazab-privatesend_tests.o' failed

### ISSUE THREAD

**Issue by wolfeye2928** [xazab/xazab#1]
build for ubuntu 16.04 fails error log 
Makefile:11426: recipe for target 'test/test_test_xazab-privatesend_tests.o' failed

**Comment by xazab** [comment]
> build for ubuntu 16.04 fails error log
> Makefile:11426: recipe for target 'test/test_test_xazab-privatesend_tests.o' failed

What branch?

**Comment by andrey3127830** [comment]
не синхронизируется кошелек совсем. старая версия на 68 процентов застревает. нвая вообще 0

**Comment by xazab** [comment]
> build for ubuntu 16.04 fails error log
> Makefile:11426: recipe for target 'test/test_test_xazab-privatesend_tests.o' failed

Kindly build again.
